### PR TITLE
Hack around blockers to update toolchain all the way to `nightly-2024-11-22` (~1.84).

### LINKED ISSUE #29: Segfault while compiling `rustc_codegen_spirv`
### Expected Behaviour
`cargo build` should finish without error.

### Example & Steps To Reproduce
Run `cargo build` after a clean clone of the repo.

## System Info

 - Rust: rustc 1.79.0-nightly (244da22fa 2024-04-23)
 - OS: macOS 15.0 (24A335)
 - GPU: integrated

## Output

```
error: could not compile `rustc_codegen_spirv` (lib)

Caused by:
  process didn't exit successfully: `/Users/schell/.rustup/toolchains/nightly-2024-04-24-aarch64-apple-darwin/bin/rustc --crate-name rustc_codegen_spirv --edition=2021 crates/rustc_codegen_spirv/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=320 --crate-type dylib --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked --cfg 'feature="default"' --cfg 'feature="use-compiled-tools"' -C metadata=5d6b9f1085555723 --out-dir /Users/schell/code/rust-gpu/target/debug/deps -C incremental=/Users/schell/code/rust-gpu/target/debug/incremental -L dependency=/Users/schell/code/rust-gpu/target/debug/deps --extern ar=/Users/schell/code/rust-gpu/target/debug/deps/libar-e3ad7146ff683a59.rlib --extern either=/Users/schell/code/rust-gpu/target/debug/deps/libeither-b182a76c8248f318.rlib --extern hashbrown=/Users/schell/code/rust-gpu/target/debug/deps/libhashbrown-d177bbe31249a900.rlib --extern indexmap=/Users/schell/code/rust-gpu/target/debug/deps/libindexmap-5721173ffd4b737f.rlib --extern itertools=/Users/schell/code/rust-gpu/target/debug/deps/libitertools-91ee06ba4bd713a5.rlib --extern lazy_static=/Users/schell/code/rust-gpu/target/debug/deps/liblazy_static-4bc53d643ec30e40.rlib --extern libc=/Users/schell/code/rust-gpu/target/debug/deps/liblibc-71b3be213458ada3.rlib --extern num_traits=/Users/schell/code/rust-gpu/target/debug/deps/libnum_traits-893caca608ed540b.rlib --extern once_cell=/Users/schell/code/rust-gpu/target/debug/deps/libonce_cell-e9b1da7b0201a63a.rlib --extern regex=/Users/schell/code/rust-gpu/target/debug/deps/libregex-b32f0d5f03e3e84d.rlib --extern rspirv=/Users/schell/code/rust-gpu/target/debug/deps/librspirv-2abab5c81971212b.rlib --extern rustc_demangle=/Users/schell/code/rust-gpu/target/debug/deps/librustc_demangle-61ad1dd711dcb489.rlib --extern rustc_codegen_spirv_types=/Users/schell/code/rust-gpu/target/debug/deps/librustc_codegen_spirv_types-1b2da75106876b67.rlib --extern sanitize_filename=/Users/schell/code/rust-gpu/target/debug/deps/libsanitize_filename-86f3198c840fea75.rlib --extern smallvec=/Users/schell/code/rust-gpu/target/debug/deps/libsmallvec-814122e6d785094d.rlib --extern spirt=/Users/schell/code/rust-gpu/target/debug/deps/libspirt-3313c9c2493bc97b.rlib --extern spirv_tools=/Users/schell/code/rust-gpu/target/debug/deps/libspirv_tools-ffda6275029880c3.rlib -Dunsafe_code '-Wclippy::all' '-Wclippy::await_holding_lock' '-Wclippy::char_lit_as_u8' '-Wclippy::checked_conversions' '-Wclippy::dbg_macro' '-Wclippy::debug_assert_with_mut_call' '-Wclippy::doc_markdown' '-Wclippy::empty_enum' '-Wclippy::enum_glob_use' '-Wclippy::exit' '-Wclippy::expl_impl_clone_on_copy' '-Wclippy::explicit_deref_methods' '-Wclippy::explicit_into_iter_loop' '-Wclippy::fallible_impl_from' '-Wclippy::filter_map_next' '-Wclippy::flat_map_option' '-Wclippy::float_cmp_const' '-Wclippy::fn_params_excessive_bools' '-Wclippy::from_iter_instead_of_collect' '-Wclippy::if_let_mutex' '-Wclippy::implicit_clone' '-Wclippy::imprecise_flops' '-Wclippy::inefficient_to_string' '-Wclippy::invalid_upcast_comparisons' '-Wclippy::large_digit_groups' '-Wclippy::large_stack_arrays' '-Wclippy::large_types_passed_by_value' '-Wclippy::let_unit_value' '-Wclippy::linkedlist' '-Wclippy::lossy_float_literal' '-Wclippy::macro_use_imports' '-Wclippy::manual_ok_or' '-Wclippy::map_err_ignore' '-Wclippy::map_flatten' '-Wclippy::map_unwrap_or' '-Wclippy::match_on_vec_items' '-Wclippy::match_same_arms' '-Wclippy::match_wild_err_arm' '-Wclippy::match_wildcard_for_single_variants' '-Wclippy::mem_forget' '-Wclippy::mismatched_target_os' '-Wclippy::missing_enforced_import_renames' '-Wclippy::mut_mut' '-Wclippy::mutex_integer' '-Wclippy::needless_borrow' '-Wclippy::needless_continue' '-Wclippy::needless_for_each' '-Wclippy::option_option' '-Wclippy::path_buf_push_overwrite' '-Wclippy::ptr_as_ptr' '-Wclippy::rc_mutex' '-Wclippy::ref_option_ref' '-Wclippy::rest_pat_in_fully_bound_structs' '-Wclippy::same_functions_in_if_condition' '-Wclippy::semicolon_if_nothing_returned' '-Wclippy::single_match_else' '-Wclippy::string_add_assign' '-Wclippy::string_add' '-Wclippy::string_lit_as_bytes' '-Wclippy::string_to_string' '-Wclippy::todo' '-Wclippy::trait_duplication_in_bounds' '-Wclippy::unimplemented' '-Wclippy::unnested_or_patterns' '-Wclippy::unused_self' '-Wclippy::useless_transmute' '-Wclippy::verbose_file_reads' '-Wclippy::zero_sized_map_values' -Wfuture_incompatible -Wnonstandard_style -Wrust_2018_idioms -Aunsafe_code -L native=/Users/schell/code/rust-gpu/target/debug/build/spirv-tools-sys-a44f67dd6078deef/out` (signal: 11, SIGSEGV: invalid memory reference)
```

### PR DESCRIPTION
**Pull request by eddyb**
*Each commit should be reviewed separately.*

- fixes #29

<sub>(in theory, I still need to test it, which is why this is "Draft" - ideally we can test debug mode builds in CI? hopefully without a lot of time wasted etc. - also, are there any more issues that updating nightly fixes?)</sub>

That issue is in fact how I got the idea for the worst hack of this (see the very end of https://github.com/Rust-GPU/rust-gpu/issues/29#issuecomment-2503586682).

---

The terrible hacks making this possible:
- `rustc_codegen_ssa`'s source code is now copied out of the sysroot *and patched*
  - (see `crates/rustc_codegen_spirv/build.rs` for most of the implementation)
  - allows reintroducing _**typed**_ (instead of merely `(Size, Align)`-shaped)
    `alloca`s (LLVM's name for "stack slots"/function-local variables),
    previously removed in https://github.com/rust-lang/rust/pull/122053
  - the modified version is dubbed `pqp_cg_ssa` to make it harder to confuse
    (where "pqp" = "pre-`qptr`-patched", a nod to the eventual real solution)
  - most of the difficulty isn't with getting the `rustc_codegen_ssa` source
    (as the `rustc-dev` rustup component places it in the sysroot),
    *or* the patches (most of which are very simple!), but rather *the build*
    ("nesting a crate as a module in another crate" + Cargo deps issues)
  - unblocks updating beyond `nightly-2024-04-24` (last nightly before that PR)
- `check_well_formed` query is bypassed for very simple `#[repr(simd)]` `struct`s
  - effectively undoes (for now) https://github.com/rust-lang/rust/pull/129403
  - avoids having to come up with a replacement for our use of `#[repr(simd)]`,
    *and* moving `glam` over to it
    <sub>(something as simple as `#[spirv(vector)]` *might* work, but 1. we didn't want `glam` depending on `spirv-std*` crates and 2. I haven't tried this theory, we might be relying a lot on `rustc`'s SIMD concepts)</sub>
  - unblocks updating to `nightly-2024-10-12` (~1.83) and beyond
- `check_mono_item` query is completely disabled (replaced with a noop)
  - effectively undoes https://github.com/rust-lang/rust/pull/132173
    (NB: query was renamed by https://github.com/rust-lang/rust/pull/132843)
  - this is more `#[repr(simd)]` fallout (more of a warning for now anyway)
  - unblocks updating to `nightly-2024-11-22` (~1.84) and beyond

We're lucky that 1.83 just released, so the "~1.84" nightly this PR gets to is currently in beta (to become stable 1.84 in 5 more weeks or so), so if we release Rust-GPU 0.10 in the next few weeks, we won't be behind stable *at all*.

---

There is also at least one refactor (`SpirvConst::Scalar`) which could be moved into its own PR, as well as a much smaller fix for `panic_nounwind_fmt` (not directly relevant, just that the `format_args!` "decompiler" changes I had for some of these nightlies had assumed that change originally).

### CODE REVIEW

File: crates/rustc_codegen_spirv/build.rs [hunk 1]
```diff
@@ -63,21 +73,189 @@ fn check_toolchain_version() -> Result<(), Box<dyn Error>> {
...
     }
 
     Ok(())
 }
 
+/// Copy `rustc_codegen_ssa` (from the `rustc-dev` component) and patch it to
+/// produce a "pqp" ("pre-`qptr`-patched") version that maintains compatibility
+/// with "legacy" Rust-GPU pointer handling (mainly typed `alloca`s).
+//
+// FIXME(eddyb) get rid of this as soon as it's not needed anymore.
```
Comment (LegNeato) [inline crates/rustc_codegen_spirv/build.rs:93]: We should have a task written for this so we don't lose track

File: crates/rustc_codegen_spirv/build.rs [hunk 2]
```diff
@@ -63,21 +73,189 @@ fn check_toolchain_version() -> Result<(), Box<dyn Error>> {
...
+                    } else if line == "#[macro_use]" || line.starts_with("extern crate ") {
+                        src += "// ";
+                        writeln(&mut cg_ssa_lib_rs_extern_crates, line);
+                    }
+                    writeln(&mut src, line);
+                }
+            }
+
+            // HACK(eddyb) "typed alloca" patches.
+            if relative_path == Path::new("src/traits/builder.rs") {
```
Comment (LegNeato) [inline crates/rustc_codegen_spirv/build.rs:182]: Should these just be .patch files that are then applied rather than being in the source?

File: crates/rustc_codegen_spirv/src/abi.rs [hunk 3]
```diff
@@ -168,14 +169,110 @@ pub(crate) fn provide(providers: &mut Providers) {
...
+
+    // HACK(eddyb) work around https://github.com/rust-lang/rust/pull/129403
+    // banning "struct-style" `#[repr(simd)]` (in favor of "array-newtype-style"),
+    // by simply bypassing "type definition WF checks" for affected types, which:
+    // - can only really be sound for types with trivial field types, that are
+    //   either completely non-generic (covering most `#[repr(simd)]` `struct`s),
+    //   or *at most* one generic type parameter with no bounds/where clause
+    // - relies on upstream `layout_of` not having had the non-array logic removed
+    //
+    // FIXME(eddyb) remove this once migrating beyond `#[repr(simd)]` becomes
```
Comment (LegNeato) [inline crates/rustc_codegen_spirv/src/abi.rs:189]: Prob want a task for this too.

File: crates/rustc_codegen_spirv/src/builder/builder_methods.rs [hunk 4]
```diff
@@ -917,9 +920,47 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
...
+                .find_map(|(index, inst)| {
+                    if inst.class.opcode != Op::Variable {
+                        Some(InsertPoint::FromBegin(index))
+                    } else {
+                        None
+                    }
+                })
+                .unwrap_or(InsertPoint::End)
+        };
+        // TODO: rspirv doesn't have insert_variable function
```
Comment (LegNeato) [inline crates/rustc_codegen_spirv/src/builder/builder_methods.rs:951]: Do we need a task on rspirv? If so we should file and link here

**Review by LegNeato — COMMENTED** [review]
I'm not really qualified to review this, some superficial comments.

File: crates/rustc_codegen_spirv/src/builder/builder_methods.rs (hunk 4 above)
Comment (eddyb) [reply crates/rustc_codegen_spirv/src/builder/builder_methods.rs:951]: This stuff is an old comment that can probably removed (expecting high-level APIs from `rspirv` is counterproductive).

File: crates/rustc_codegen_spirv/build.rs (hunk 2 above)
Comment (eddyb) [reply crates/rustc_codegen_spirv/build.rs:182]: `str::replace` may be expensive but I don't want to deal with adding a whole extra dependency just to rewrite one line in each of 3 files (if there is even a good one - keep in mind this has to be inherently cross-platform).

I didn't even bother with the `regex` crate because this worked. Maybe if it's a bottleneck we could try to fix that but I don't want to make this stuff too cushy (ideally we can nuke it just after we release 0.10).

**Comment by eddyb** [comment]
Looking like `codegen-units = 1` + `-Zshare-generics=off` was enough to push Windows under the MSVC (or possibly file format?) 64Ki limit.

Still have some comments (https://github.com/Rust-GPU/rust-gpu/pull/170#pullrequestreview-2476642030) to address, but otherwise this seems to work.

**Comment by LegNeato** [comment]
Are we ready to take this out of draft @eddyb ?

File: crates/rustc_codegen_spirv/build.rs (hunk 1 above)
Comment (eddyb) [reply crates/rustc_codegen_spirv/build.rs:93]: - https://github.com/Rust-GPU/rust-gpu/issues/182

File: crates/rustc_codegen_spirv/src/abi.rs (hunk 3 above)
Comment (eddyb) [reply crates/rustc_codegen_spirv/src/abi.rs:189]: - https://github.com/Rust-GPU/rust-gpu/issues/182

**Review by Firestar99 — APPROVED** [review]
stamping as requested by @eddyb
